import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

const dir = path.resolve( path.dirname( fileURLToPath( import.meta.url ) ), '..' );
const read = file => fs.readFileSync( path.join( dir, file ), 'utf8' );
const js = read( 'assets/js/city-contrib.js' );
const adminJs = read( 'assets/js/admin.js' );
const css = read( 'assets/css/city-contrib.css' );
const adminCss = read( 'assets/css/admin.css' );
const db = read( 'includes/class-cc-activator.php' );
const rating = read( 'includes/modules/class-cc-rating.php' );
const contrib = read( 'includes/modules/class-cc-contrib.php' );
const auth = read( 'includes/modules/class-cc-auth.php' );
const files = fs.readdirSync( path.join( dir, 'includes/modules' ) ).filter( f => f.endsWith( '.php' ) );
const allModules = files.map( f => read( 'includes/modules/' + f ) ).join( '\n' );

assert.ok( Buffer.byteLength( js ) + Buffer.byteLength( adminJs ) < 30 * 1024, 'all plugin JS must be below 30KB' );
assert.ok( Buffer.byteLength( css ) + Buffer.byteLength( adminCss ) < 20 * 1024, 'all plugin CSS must be below 20KB' );
assert.equal( /jquery/i.test( js ), false, 'front-end must not use jQuery' );
assert.match( db, /UNIQUE KEY user_city \(user_id,city_id\)/, 'DB enforces one rating per city/user' );
assert.match( db, /KEY city_id \(city_id\)/ );
assert.match( db, /KEY user_created \(user_id,created_at\)/ );
assert.match( rating, /SELECT ID FROM \{\$wpdb->users\} WHERE ID = %d FOR UPDATE/ );
assert.match( rating, /SELECT ID FROM \{\$wpdb->posts\} WHERE ID = %d FOR UPDATE/ );
assert.ok( rating.indexOf( 'FOR UPDATE' ) < rating.indexOf( '$wpdb->insert(' ), 'locks must precede rating insert' );
assert.match( rating, /'ROLLBACK'/ );
assert.match( rating, /'COMMIT'/ );
assert.match( rating, /409/ );
assert.match( contrib, /register_post_status\(\s*'approved'/ );
assert.match( contrib, /register_post_status\(\s*'rejected'/ );
assert.match( contrib, /'post_status' => 'pending'/ );
assert.match( contrib, /array\( 'introduce', 'correction', 'report', 'tip' \)/ );
assert.match( auth, /otp_hourly_limit/ );
assert.match( auth, /wp_verify_nonce/ );
assert.match( allModules, /wp_get_image_editor/ );
assert.match( allModules, /image\/webp/ );
assert.match( allModules, /cc_moderator_city_ids/ );
console.log( 'city-contrib static checks: OK' );
